name: EasyLand
version: "${project.version}"
main: io.github.railgun19457.easyland.EasyLand
api-version: "1.21"
api: "1.21"
authors: [railgun19457]
description: A simple land protection plugin.
website: https://github.com/railgun19457/EasyLand

commands:
  easyland:
    description: EasyLand主命令
    aliases: [el, land]
    usage: |
      /easyland <子命令> [参数] - 玩家命令
      /easyland reload - 控制台可用
      /easyland migrate - 控制台可用
    permission: easyland.use

permissions:
  easyland.*:
    description: EasyLand所有权限
    children:
      easyland.use: true
      easyland.admin: true
  easyland.use:
    description: 使用EasyLand基本命令
    default: true
    children:
      easyland.claim: true
      easyland.abandon: true
      easyland.delete: true
      easyland.info: true
      easyland.list: true
      easyland.show: true
      easyland.trust: true
      easyland.rule: true
      easyland.rename: true
      easyland.subcreate: true
      easyland.setspawn: true
      easyland.tp: true
      easyland.select: true
  easyland.admin:
    description: EasyLand管理员权限 - OP自动拥有，可管理所有领地并绕过所有保护
    default: op
    children:
      easyland.create: true
      easyland.delete: true
      easyland.reload: true
      easyland.migrate: true
      easyland.bypass: true
      easyland.admin.manage: true
  easyland.bypass:
    description: 绕过所有领地保护
    default: op
  easyland.admin.manage:
    description: 管理任何玩家的领地
    default: op
  easyland.select:
    description: 获取领地选择工具
    default: true
  easyland.create:
    description: 创建领地（管理员命令）
    default: op
  easyland.claim:
    description: 认领领地
    default: true
  easyland.abandon:
    description: 放弃领地
    default: true
  easyland.delete:
    description: 删除领地（自己的领地或管理员）
    default: true
  easyland.info:
    description: 查看领地信息
    default: true
  easyland.list:
    description: 查看领地列表
    default: true
  easyland.show:
    description: 显示领地边界
    default: true
  easyland.trust:
    description: 信任/取消信任玩家
    default: true
  easyland.rule:
    description: 管理领地保护规则
    default: true
  easyland.rename:
    description: 重命名领地
    default: true
  easyland.subcreate:
    description: 创建子领地
    default: true
  easyland.setspawn:
    description: 设置领地传送点
    default: true
  easyland.tp:
    description: 传送到领地
    default: true
  easyland.migrate:
    description: 从旧版YAML文件迁移数据到SQLite数据库（管理员命令）
    default: op
