# Easyland 插件配置

#每个玩家可获得的最大领地数量
max-lands-per-player: 5

#每个领地可包含的最大区块数量
max-chunks-per-land: 256

#显示领地边界粒子类型（可选：FLAME、SMOKE、PORTAL、HEART等，详见Particle枚举）
land-boundary-particle: firework

#显示领地边界的默认时间（秒）
show-duration-seconds: 10

#显示领地边界的最大时间（秒）
max-show-duration-seconds: 300

#是否保护领地内不被生物破坏（如苦力怕爆炸、末影人搬运等）
protect-from-mob-griefing: true
