name: Easyland
main: com.example.easyland.EasylandPlugin
version: 1.0
api-version: 1.21
commands:
  easyland:
    description: 领地管理指令
    usage: /easyland select | create | claim | unclaim | trust <玩家名> | untrust <玩家名>
    aliases: [el, land]
    permission-message: §c你没有权限使用此指令！
description: A PaperMC 1.21.4 plugin template.
permissions:
  easyland.select:
    description: 使用 /easyland select 选择领地的权限
    default: op
  easyland.create:
    description: 使用 /easyland create 创建无主领地的权限
    default: op
  easyland.claim:
    description: 使用 /easyland claim 认领领地的权限
    default: true
  easyland.unclaim:
    description: 使用 /easyland unclaim 放弃领地的权限
    default: true
  easyland.trust:
    description: 使用 /easyland trust 信任他人的权限
    default: true
  easyland.untrust:
    description: 使用 /easyland untrust 取消信任的权限
    default: true
  easyland.show:
    description: 使用 /easyland show 显示领地范围的权限
    default: true
  easyland.list:
    description: 使用 /easyland list 查看领地列表的权限
    default: true
  easyland.remove:
    description: 使用 /easyland remove 删除领地的权限
    default: op
  easyland.bypass:
    description: 绕过领地保护的管理员权限
    default: op
